### ISSUE TITLE
log-file with model parameters

### ISSUE THREAD

**Issue by johanvdw** [inbo/niche_vlaanderen#19]
The goal is having a report of which input files were used (grids and codetables).
I think this could also be present inside the Python module, eg a print of a Niche object should show the same results.

**Comment by johanvdw** [comment]
We can keep a yaml format compatible with the input format, so you can use the logfile to rerun the model, or copy/paste from it

Eg.
```
# Niche Vlaanderen version: 0.0.1

package_versions:
  pandas: 0.21.0
  numpy: 1.13.3
  rasterio: 0.36.0
  gdal: 2.1.2

input_layers:
  conductivity: Ingrids/mineraal
  inundation_acidity: Ingrids/ovstr_z
  inundation_nutrient: Ingrids/ovstr_z
  inundation_vegetation: Ingrids/nulgrid
  management: Ingrids/beheer
  nitrogen_animal: Ingrids/bemest_d
  nitrogen_atmospheric: Ingrids/dep
  nitrogen_fertilizer: Ingrids/bemest_k
  rainwater: Ingrids/nulgrid
  seepage: Ingrids/kwel
  soil_code: Ingrids/bodemveen
  mhw: 5
  mlw: 30
  msw: 10

model_results:
  V1: xxx
```
