### ISSUE TITLE
Add travis deploy for documentation towards github-pages

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/niche_vlaanderen#7]
As we use CI, we can also add automated updates of the documentation as a deployment step, pushing the docs to the `gh-pages` repo, analog to https://github.com/inbo/pywhip/blob/master/.travis.yml

This basically means adding a deployment step to the Travis file and activating the keys:

```
deploy:
  provider: script
  script:
    - travis-sphinx --source=docs --nowarn build
    - travis-sphinx deploy
  on:
      python: 3.5
```

I'll add this asap.
